# -*- coding: utf-8 -*-
"""clean_and_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JrKBCN3Gtl5F1cxegH07T9nSlgF3Ns5k

## Load & Inspect
"""

import pandas as pd
import numpy as np

orders = pd.read_csv('orders.csv')
orders.shape

customers = pd.read_csv('customers.csv')
customers.shape

products = pd.read_csv('products.csv')
products.shape

"""## Standardize payment_method casing"""

orders['payment_method'].unique()

orders['payment_method'] = orders['payment_method'].str.strip().str.upper()
unique_payment_methods = orders['payment_method'].unique()
print(f"Unique payment methods: {unique_payment_methods}")
print(f"Number of unique payment methods: {unique_payment_methods.size}")

orders.head()

"""## Remove duplicate orders"""

import pandas as pd
key_columns = [
    "customer_id",
    "product_id",
    "order_date",
    "quantity",
    "discount_pct",
    "payment_method",
    "rating",
    "returned"
]

duplicate_mask = orders.duplicated(
    subset=key_columns,
    keep="first"
)

dropped_orders = orders[duplicate_mask]

print("Duplicate rows:", duplicate_mask.sum())
print("Dropped order IDs:", dropped_orders["order_id"].tolist())

orders_clean = orders[~duplicate_mask].copy()

print("orders_clean shape:", orders_clean.shape)

print(type(orders_clean))

print(orders_clean.shape)

"""## Impute missing values"""

print("Missing discount_pct:", orders_clean["discount_pct"].isnull().sum())
print("Missing rating:", orders_clean["rating"].isnull().sum())

orders_clean["discount_pct"] = orders_clean["discount_pct"].fillna(0)

rating_median = orders_clean["rating"].median()
print("Rating median:", rating_median)

orders_clean["rating"] = orders_clean["rating"].fillna(rating_median)
print(orders_clean[["discount_pct", "rating"]].isnull().sum())

"""## Merge and reconcile"""

print(orders_clean.shape)
print(products.shape)
print(customers.shape)

orders_merged = orders_clean.merge(
    products,
    on="product_id",
    how="left"
)
print(orders_merged.shape)

orders_merged = orders_merged.merge(
    customers,
    on="customer_id",
    how="left"
)
print(orders_merged.shape)

orders_merged["order_value"] = (
    orders_merged["quantity"]
    * orders_merged["price"]
    * (1 - orders_merged["discount_pct"] / 100)
)

total_order_value = orders_merged["order_value"].sum()

print("Total order value:", round(total_order_value, 2))

# Calculate order_value for the 5 dropped duplicate rows independently
dropped_orders = dropped_orders.merge(
    products[["product_id", "price"]],
    on="product_id",
    how="left"
)

dropped_orders["order_value"] = (
    dropped_orders["quantity"]
    * dropped_orders["price"]
    * (1 - dropped_orders["discount_pct"].fillna(0) / 100)
)

dropped_value = dropped_orders["order_value"].sum()

"""**Reconciliation note:** The Part 1 total order value was ₹99,860.20, while the
cleaned 175-row dataset has a total order value of ₹97358.30.
The exact delta of ₹2501.90 is attributable to the
5 duplicate rows removed in Task 3 (O0176, O0177, O0178, O0179, and O0180),
whose combined order_value is independently calculated as ₹2501.90.
The discount_pct and rating imputations did not change the order_value total,
because discount_pct missing values were filled with 0 and rating is not used
in the order_value calculation.

## IQR outlier detection on quantity
"""

Q1 = orders_merged["quantity"].quantile(0.25)
Q3 = orders_merged["quantity"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower)
print("Upper bound:", upper)

orders_merged["is_outlier"] = (
    (orders_merged["quantity"] < lower) |
    (orders_merged["quantity"] > upper)
)

outliers = orders_merged[orders_merged["is_outlier"]]

print(outliers[["order_id", "quantity", "is_outlier"]])

print("Number of outliers:", orders_merged["is_outlier"].sum())

"""## Hypothesis: Does COD have a higher return rate?"""

print("\nHypothesis: COD has a higher return rate than CARD and UPI.")

return_rate = (
    orders_merged
    .groupby("payment_method")["returned"]
    .agg(["count", "mean"])
)

print("\nReturn rate by payment method:")
print(return_rate)

print("\nReturn rates (%):")
print((return_rate["mean"] * 100).round(1))

"""Hypothesis: Confirmed

## Multi-level segmentation
"""

print(orders_merged.columns.tolist())

# Task 8 — Multi-level segmentation

segment_return_rate = (
    orders_merged
    .groupby(["payment_method", "city_tier"])["returned"]
    .agg(["count", "mean"])
)

print("\nReturn rate by payment method and city tier:")
print(segment_return_rate)

print("\nReturn rates (%):")

for (payment_method, city_tier), row in segment_return_rate.iterrows():
    print(
        f"{payment_method} + Tier-{city_tier}: "
        f"{row['mean'] * 100:.1f}% "
        f"({int(row['count'])} orders)"
    )

"""Highest-risk segment: COD + Tier-2 cities at 54.5% (22 orders).

COD risk is not uniform across city tiers: Tier-1 COD orders have a 37.5% return rate (32 orders), while Tier-2 COD orders have a 54.5% return rate (22 orders).

## Correlation analysis
"""

corr_cols = ["rating", "returned", "discount_pct", "quantity"]

corr_matrix = orders_merged[corr_cols].corr()

print("\nCorrelation matrix:")
print(corr_matrix)

print("\nCorrelation-strength bands:")
print("Negligible: |r| < 0.2")
print("Weak:       0.2 <= |r| < 0.4")
print("Moderate:   0.4 <= |r| < 0.7")
print("Strong:     0.7 <= |r| <= 1.0")

pairs = [
    ("rating", "returned"),
    ("rating", "discount_pct"),
    ("rating", "quantity"),
    ("returned", "discount_pct"),
    ("returned", "quantity"),
    ("discount_pct", "quantity")
]

for col1, col2 in pairs:
    r = corr_matrix.loc[col1, col2]

    if abs(r) < 0.2:
        band = "negligible"
    elif abs(r) < 0.4:
        band = "weak"
    elif abs(r) < 0.7:
        band = "moderate"
    else:
        band = "strong"

    print(f"{col1} vs {col2}: r = {r:.2f} → {band}")

discount_return_corr = corr_matrix.loc["discount_pct", "returned"]

print(
    f"\nHypothesis: Higher discounts reduce returns → "
    f"Busted (correlation = {discount_return_corr:.2f}, negligible)"
)

"""## Outlier-corrected time series"""

# Convert order_date to datetime
orders_merged["order_date"] = pd.to_datetime(orders_merged["order_date"])

# Extract year-month
orders_merged["year_month"] = orders_merged["order_date"].dt.to_period("M")

# 1. Monthly order value INCLUDING outliers
monthly_total = (
    orders_merged
    .groupby("year_month")["order_value"]
    .sum()
)

print("\nMonthly order value INCLUDING outliers:")
for month, value in monthly_total.items():
    print(f"{month}: {value:.2f}")


# 2. Monthly order value EXCLUDING Task 6 outliers
monthly_corrected = (
    orders_merged[~orders_merged["is_outlier"]]
    .groupby("year_month")["order_value"]
    .sum()
)

print("\nMonthly order value EXCLUDING outliers:")
for month, value in monthly_corrected.items():
    print(f"{month}: {value:.2f}")

"""**Interpretation:**
January's apparent lead is an artifact of the two bulk orders landing in January — O0011 on 2026-01-28 and O0098 on 2026-01-10. Once these two Task 6 outlier orders are excluded, March becomes the genuine peak month. This demonstrates why the outliers were flagged before performing the time-series analysis.**

"""

import os

os.makedirs("visualizations", exist_ok=True)

print("Folder ready")

import matplotlib.pyplot as plt

# Calculate return rate by payment method
return_rate = (
    orders_clean.groupby("payment_method")["returned"]
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

print(return_rate)

plt.figure(figsize=(8, 5))

bars = plt.bar(
    return_rate.index,
    return_rate.values
)

# Add exact percentage labels
for bar, rate in zip(bars, return_rate.values):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height(),
        f"{rate:.1f}%",
        ha="center",
        va="bottom"
    )

plt.xlabel("Payment Method")
plt.ylabel("Return Rate (%)")
plt.title("COD Returns at 44.4% — 3x Card")

plt.tight_layout()

plt.savefig(
    "visualizations/return_rate_by_payment.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

import os

os.makedirs("visualizations", exist_ok=True)

import matplotlib.pyplot as plt

# Use the outlier-corrected monthly revenue from Task 10
months = monthly_corrected.index.astype(str)
revenue = monthly_corrected.values

# Find the actual peak month
peak_month = monthly_corrected.idxmax()
peak_revenue = monthly_corrected.max()

# Create line chart
plt.figure(figsize=(9, 5))

plt.plot(
    months,
    revenue,
    marker="o"
)

# Add exact revenue labels
for month, value in zip(months, revenue):
    plt.text(
        month,
        value,
        f"₹{value:,.2f}",
        ha="center",
        va="bottom"
    )

plt.xlabel("Month")
plt.ylabel("Revenue (₹)")

plt.title(
    f"Outlier-Corrected Monthly Revenue — Peak: {peak_month}"
)

plt.xticks(rotation=45)

plt.tight_layout()

# Save the chart
plt.savefig(
    "visualizations/monthly_revenue_trend.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

print(f"Peak month: {peak_month}")
print(f"Peak revenue: ₹{peak_revenue:,.2f}")

import os

print(os.listdir("visualizations"))

from google.colab import files

files.download("visualizations/return_rate_by_payment.png")
files.download("visualizations/monthly_revenue_trend.png")

